# Force Railway to install .NET 8 SDK
NIXPACKS_PKGS = "dotnet-sdk_8"

[build]
builder = "NIXPACKS"
buildCommand = "cd backend && dotnet restore && dotnet publish -c Release -o ../out"

[deploy]
startCommand = "dotnet out/DialyGo.dll"
