// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MobileDialysisDbContext))]
    [Migration("20251023080510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adminId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("AdminId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("appointmentDate");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("NurseId")
                        .HasColumnType("int")
                        .HasColumnName("nurseId");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Scheduled','Completed','Cancelled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Scheduled'");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("truckId");

                    b.HasKey("AppointmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DoctorId" }, "idx_appointment_doctor");

                    b.HasIndex(new[] { "NurseId" }, "idx_appointment_nurse");

                    b.HasIndex(new[] { "PatientId" }, "idx_appointment_patient");

                    b.HasIndex(new[] { "TruckId" }, "idx_appointment_truck");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("backend.Models.Appointmentdetail", b =>
                {
                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("appointmentDate");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("doctorName");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("NurseName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nurseName");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("patientName");

                    b.Property<string>("Status")
                        .HasColumnType("enum('Scheduled','Completed','Cancelled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Scheduled'");

                    b.Property<string>("TruckPlate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("truckPlate");

                    b.ToTable((string)null);

                    b.ToView("appointmentdetails", (string)null);
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doctorId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phoneNumber");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialization");

                    b.HasKey("DoctorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("backend.Models.LoginSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sessionId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ipAddress");

                    b.Property<DateTime?>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("loginTime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("logoutTime");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("userAgent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("SessionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_loginsession_user");

                    b.ToTable("LoginSession", (string)null);
                });

            modelBuilder.Entity("backend.Models.Nurse", b =>
                {
                    b.Property<int>("NurseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nurseId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NurseId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("NurseId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email2");

                    b.ToTable("Nurse", (string)null);
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("enum('Male','Female','Other')")
                        .HasColumnName("gender");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("text")
                        .HasColumnName("medicalHistory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phoneNumber");

                    b.HasKey("PatientId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email3");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("backend.Models.Smsnotification", b =>
                {
                    b.Property<int>("SmsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("smsId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SmsId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("senderId");

                    b.Property<string>("SenderRole")
                        .HasColumnType("enum('Doctor','Nurse')")
                        .HasColumnName("senderRole");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sentAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SentBy")
                        .HasColumnType("enum('System','Nurse','Doctor')")
                        .HasColumnName("sentBy");

                    b.HasKey("SmsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "idx_sms_patient");

                    b.ToTable("SMSNotification", (string)null);
                });

            modelBuilder.Entity("backend.Models.TreatmentRecord", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("treatmentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreatmentId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<DateTime?>("TreatmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("treatmentDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TreatmentDetails")
                        .HasColumnType("text")
                        .HasColumnName("treatmentDetails");

                    b.HasKey("TreatmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AppointmentId" }, "fk_treatment_appointment");

                    b.HasIndex(new[] { "PatientId" }, "idx_treatment_patient");

                    b.ToTable("TreatmentRecord", (string)null);
                });

            modelBuilder.Entity("backend.Models.Truck", b =>
                {
                    b.Property<int>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("truckId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TruckId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("currentLocation");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("licensePlate");

                    b.HasKey("TruckId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LicensePlate" }, "licensePlate")
                        .IsUnique();

                    b.ToTable("Truck", (string)null);
                });

            modelBuilder.Entity("backend.Models.TruckAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignmentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly?>("DateAssigned")
                        .HasColumnType("date")
                        .HasColumnName("dateAssigned");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("truckId");

                    b.HasKey("AssignmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TruckId" }, "fk_truckassignment_truck");

                    b.HasIndex(new[] { "PatientId" }, "idx_truckassignment_patient");

                    b.ToTable("TruckAssignment", (string)null);
                });

            modelBuilder.Entity("backend.Models.TruckMaintenance", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maintenanceId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("MaintenanceDate")
                        .HasColumnType("date")
                        .HasColumnName("maintenanceDate");

                    b.Property<DateOnly?>("NextServiceDue")
                        .HasColumnType("date")
                        .HasColumnName("nextServiceDue");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("truckId");

                    b.HasKey("MaintenanceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TruckId" }, "fk_maintenance_truck");

                    b.ToTable("TruckMaintenance", (string)null);
                });

            modelBuilder.Entity("backend.Models.TruckStaffAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignmentId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date")
                        .HasColumnName("dateAssigned");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("enum('Doctor','Nurse')")
                        .HasColumnName("role");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staffId");

                    b.Property<int>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("truckId");

                    b.HasKey("AssignmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TruckId" }, "idx_truckstaff_truck");

                    b.ToTable("TruckStaffAssignment", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<int>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("relatedId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "fk_user_role");

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("backend.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "roleName")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("backend.Models.Userdetailsview", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fullName");

                    b.Property<int>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("relatedId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialization");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("userdetailsview", (string)null);
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.HasOne("backend.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("appointment_ibfk_2");

                    b.HasOne("backend.Models.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("NurseId")
                        .HasConstraintName("appointment_ibfk_3");

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("appointment_ibfk_1");

                    b.HasOne("backend.Models.Truck", "Truck")
                        .WithMany("Appointments")
                        .HasForeignKey("TruckId")
                        .HasConstraintName("appointment_ibfk_4");

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("backend.Models.LoginSession", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("LoginSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_loginsession_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Smsnotification", b =>
                {
                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("Smsnotifications")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("fk_sms_patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.TreatmentRecord", b =>
                {
                    b.HasOne("backend.Models.Appointment", "Appointment")
                        .WithMany("TreatmentRecords")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("fk_treatment_appointment");

                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("TreatmentRecords")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("fk_treatment_patient");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("backend.Models.TruckAssignment", b =>
                {
                    b.HasOne("backend.Models.Patient", "Patient")
                        .WithMany("TruckAssignments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("fk_truckassignment_patient");

                    b.HasOne("backend.Models.Truck", "Truck")
                        .WithMany("TruckAssignments")
                        .HasForeignKey("TruckId")
                        .HasConstraintName("fk_truckassignment_truck");

                    b.Navigation("Patient");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("backend.Models.TruckMaintenance", b =>
                {
                    b.HasOne("backend.Models.Truck", "Truck")
                        .WithMany("TruckMaintenances")
                        .HasForeignKey("TruckId")
                        .HasConstraintName("fk_maintenance_truck");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("backend.Models.TruckStaffAssignment", b =>
                {
                    b.HasOne("backend.Models.Truck", "Truck")
                        .WithMany("TruckStaffAssignments")
                        .HasForeignKey("TruckId")
                        .IsRequired()
                        .HasConstraintName("truckstaffassignment_ibfk_1");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Appointment", b =>
                {
                    b.Navigation("TreatmentRecords");
                });

            modelBuilder.Entity("backend.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("backend.Models.Nurse", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("backend.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Smsnotifications");

                    b.Navigation("TreatmentRecords");

                    b.Navigation("TruckAssignments");
                });

            modelBuilder.Entity("backend.Models.Truck", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TruckAssignments");

                    b.Navigation("TruckMaintenances");

                    b.Navigation("TruckStaffAssignments");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("LoginSessions");
                });

            modelBuilder.Entity("backend.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
